### ISSUE TITLE
Размер шрифта в поле ввода

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vacuum-im/vacuum-im#779]
```
Здравствуйте!

Небольшой фичреквест. Хотелось бы иметь 
возможность изменять параметры шрифта (в 
частности, его размер) в поле ввода. Может, 
это уже реализовано, но в настройках ничего 
похожего не нашел, там только параметры 
шрифта в окнах конференций, чатов и так 
далее.
```

Original issue reported on code.google.com by `1.ekzit...@gmail.com` on 26 Nov 2013 at 3:07

**Comment by Lion34** [comment]
duplicate of #481

**Comment by Urvdmih** [comment]
Не понятно почему закрыли этот issue. Вот у меня возникла проблема в крайнем билде, что шрифт в поле вввода стал микроскопическим, а как поправить не знаю, настроек для поля ввода практически нет (во всяком случае для шрифтов)... Для примера прикладываю изображение. Сверху нормальный шрифт, снизу - то как печатает сейчас в поле ввода.
![vacuum_HaViwp26Ef](https://user-images.githubusercontent.com/9265883/139796829-4921992c-8dd4-46a7-9c0a-f4d7cc1b3eab.png)

**Comment by EGD** [comment]
Настройки шрифта для поля ввода берутся из системы.

**Comment by Urvdmih** [comment]
> Настройки шрифта для поля ввода берутся из системы.

Хотелось бы 
1) подробностей; 
2) знать зачем так сделано? Это не удобно...
И почему если берется из системы, то мне помогло смена значения 6,25 на 10 в этой строке файла настроек <editor-base-font-size type="6">6.25</editor-base-font-size>, это какой-то множитель разве?

**Comment by Occisor** [comment]
Есть-ли подвижки с данной проблемой, а также размером шрифтов ростера, списка контактов в конференции и вкладок? Или может какой костыль?
