### ISSUE TITLE
Ошибка квитирования SSL (vacuum-im+openfire)

### ISSUE THREAD

**Issue by pan1c** [vacuum-im/vacuum-im#860]
Здравствуйте.
Текущая стабильная версия vacuum-im (1.2.4.2369) не работает с openfire 3.10

Ошибка квитирования SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.

Ubuntu 14.04
Windows 7

Fix pls.

Я так понимаю в 1.3 исправлено, но сроки выхода 1.3 в релиз неизвестны?)

**Comment by imax9000** [comment]
Можно попробовать подложить OpenSSL посвежее, например http://indy.fulgan.com/SSL/openssl-0.9.8zf-i386-win32.zip или http://indy.fulgan.com/SSL/openssl-1.0.2a-i386-win32.zip

**Comment by krab** [comment]
Собранный 2010 студией 1.0.2a https://drive.google.com/file/d/0BwqyzjRJXbpla1AyUllScWs4eXc/view?usp=sharing

**Comment by Lion34** [comment]
Это не из-за SSL, раньше плохо работало автоопределение протокола и пришлось явно указать использовать SSLv3, а теперь он видать отключен в OpenFire. Похоже придется выпустить 1.2.5.

см. коммит 334a9aaeba59f51b39dc32c42c6d1d4105d755f5

**Comment by Lion34** [comment]
Выпустил версию 1.2.5 с исправлением.

**Comment by WCSN** [comment]
После перехода на 1.2.5  не соединяется с сервером.

QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv3_server_method

любые попытки что либо изменить в настройка не влияют на ситуацию.

**Comment by Lion34** [comment]
А какая у вас версия сервера?

**Comment by WCSN** [comment]
openfire 3.6 или 3.8   нет доступа к сервру - где можно в вакууме глянуть есть у него лог?
Да... клиент вакуум под фрю.

**Comment by Lion34** [comment]
Вам надо обновить сервер или вернуться на версию 1.2.4, лучше первое.

**Comment by WCSN** [comment]
странно... по идее всё-таки клиент должен учитывать что там с сервером. тем более что 1.2.4 нормально работал :(

**Comment by Lion34** [comment]
Насколько я помню, автоопределение версии SSL в Qt4 не корректно работает со старой версией  OpenFire из-за чего пришлось её отключить в версии 1.2.4, но с выходом новой версии OpenFire автоопределение стало работать нормально, а тот фиксированное значение в 1.2.4 перестало работать, по этому пришлось выпускать 1.2.5. Получается, что теперь новая версия не работает со старым OpenFire и наоборот.

**Comment by WCSN** [comment]
ясно ... а какой нить if поставить при проверке версии сервера ведь можно... 
ладно что-нить придумаю :)... спасибо.
