### ISSUE TITLE
не работает локальная история с openfire 3.10

### ISSUE THREAD

**Issue by black-magius** [vacuum-im/vacuum-im#862]
Замечена следующая проблема
после обновления сервера с 3,6 на 3,10 перестала сохраняться локальная история
попытки играть с настройками истории в клиенте ничего не дали 
пробовали на версиях клиента 1,2,1 и 1,3,0

сейчас проблема решена путем отключения плагина оперфаера для сохранения историии на сервере(Monitoring).

если я правильно понимаю клиент видя возможность сервера хранить историю у себя перестает ее корректно хранить локально.

**Comment by Lion34** [comment]
Да, если история сохраняется на сервере, то в локальный архив она не пишется т.к. возможна рассинхронизация. А зачем вам локальная история, если она есть на сервере?

**Comment by black-magius** [comment]
сервер не настраивался для хранения истории там просто был включен по умолчанию плагин.
галочка хранить историю на сервере в клиенте была снята, но он все равно это пытается делать. в итоге истории нет совсем.

**Comment by Lion34** [comment]
Видать плагин не позволял отключать сохранение истории на сервере в настройках и сообщал клиенту, что история все еще пишется. Если вам не нужна история на сервере, то лучше просто отключить этот плагин.

**Comment by black-magius** [comment]
мы так и поступили, но тогда вопрос зачем в настройках вакума есть возможность выключать хранение истории на сервере?
или я как то не так понимаю назначение этого флажка?

**Comment by Lion34** [comment]
Клиент посылает команду на отключение сохранение истории на сервере, но дальше все зависит от реализации на сервере, в OpenFire плагин не отключает автоматическое сохранение и если вы откроете настройки еще раз, то галочка опять будет установлена.

**Comment by black-magius** [comment]
значит это не глюк, а фича...
понял, спасибо

**Comment by Lion34** [comment]
Там кстати и бага нашлась, из-за которой результат сохранения настроек не показывался в окне.

**Comment by black-magius** [comment]
ооо, это хорошо! значит не зря вас отвлекал ))

**Comment by Yures** [comment]
Удалил этот плагин, но клиент так и не хочет сохранять локально.

**Comment by black-magius** [comment]
если удаляли через вебадминку
попробуйте проделать через консоль
зайти в openfire/plugins и тут удалить или переместить
папку monitoring и файл monitoring.jar
далее рестарт опенфаера

**Comment by Lion34** [comment]
Если в настройках стоит галка сохранения истории на сервере, значит плагин все еще работает.
