### ISSUE TITLE
поменять кнопку отправки сообщения на ctrl-enter

### ISSUE THREAD

**Issue by kullfar** [vacuum-im/vacuum-im#863]
не нашел как это сделать. в настройках нет

**Comment by Lion34** [comment]
В настройках "Горячие клавиши" должно быть.

**Comment by kullfar** [comment]
да, нашел! Клево, спасибо!
Очень нравится пока что мне этот клиент. раньше на psi сидел, но он автоджойн к конференциям через xmpp-гейтвейт к slack не умеет.
спасибо, сорри за глупый вопрос, не нашел сразу в настройках этого

**Comment by kullfar** [comment]
ожидал в пункте messages найти, где размер поля для ввода текста задается
