### ISSUE TITLE
Фильтровать недопустимые символы в добавляемых JID'ах

### ISSUE THREAD

**Issue by r-che** [vacuum-im/vacuum-im#865]
Если при добавлении контакта в конце его оказался пробел (а такое бывает когда ты копируешь строку из thunderbird например, он сам в конце пробел добавляет), то контакт добавляется вакуумом, после чего он пытается найти сервер с доменом у которого пробел в конце. Естественно не находит, что может вызвать глубокое недоумение пользователя, например у меня было "jabber.ru сервер не найден".
Было бы логично, наверное, либо не пропускать контакты с недопустимыми символами, либо обрезать пробельные символы в начале/в конце.

**Comment by Lion34** [comment]
fixed in df7e233
