### ISSUE TITLE
отправка сообщения объедененому контакту

### ISSUE THREAD

**Issue by n0n6me** [vacuum-im/vacuum-im#868]
Объединение контактов из проблемы 821 работает не совсем правильно.
В версии 1.3 один и тот же контакт вошедший с разных ресурсов, в ростере виден как как один, это хорошо.
Но,  если отправить ему сообщение, то получит все равно один из ресурсов, даже в тех случаях, когда оба ресурса имеют одинаковый приоритет. Это можно исправить? 
Сейчас vacuum сам определяет какому ресурсу отправить сообщение. Правильно  наверное функцию определения кому отправить сообщение оставить серверу?
Спасибо!

**Comment by Lion34** [comment]
Практика показывает, что лучше всего самому выбирать какому ресурсу отправлять сообщение т.к. большинство пользователей совсем не заботятся о правильной установке ресурсов и зачастую сообщения уходят не туда куда надо. Для решения этой проблемы есть расширение протокола, которое поддерживается вакуумом - Message Carbons, если оно включено, то копии сообщения отправляются на все ресурсы, которые его поддерживают, с новым ejabberd кажется должно работать. Сейчас когда открывается окно метаконтакта первым выбирается ресурс с наибольшим приоритетом и автоматически происходит переключение на тот ресурс, с которого приходит ответ.
