### ISSUE TITLE
Поиск текста по всей истории

### ISSUE THREAD

**Issue by MoonLoq** [vacuum-im/vacuum-im#871]
Доброе утро! Можете реализовать поиск по тексту по всей истории общения с пользователем? А то в форме истории сообщений поле "Поиск в истории" и кнопка "Обновить" почему-то ничего не видит.

**Comment by Lion34** [comment]
А у вас какая версия клиента?

**Comment by Lion34** [comment]
Недавно я исправлял ошибку в поиске по всей истории, если в вас версия 1.3, то вам нужно скачать последнюю сборку. В версии 1.2 поиск работает нормально.
Если ваша история хранится на сервере, то поиск по ней работать не будет т.к. эта возможность не предусмотрена стандартом и ни один сервер не позволяет выполнять полнотекстовой поиск по истории.
