### ISSUE TITLE
Join conference: History -> Last visited

### ISSUE THREAD

**Issue by az09** [vacuum-im/vacuum-im#873]
В диалоге _Join conference_ второй строкой значится _History_ со списком **открытых** конф и кнопкой _Delete_.
Обзовите его _Last visited_ что-ли, а на кнопочке предлагаю _Clear list_ написать. А то пугает :unamused:
Кстати порядок сортировки этого списка вообще не понятен. Как и назначение этого элемента без дополнительных пояснений.

**Comment by Lion34** [comment]
Это окно скоро будет полностью переделано и этого списка в нем не будет.
