### ISSUE TITLE
Не показывать пустые аватары

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#874]
Версия Vacuum-IM: 1.3.0.20151030
ОС: Windows 8.1

Как отключить пустые аватары?

В предыдщих версиях была галочка в настройках контакт-листа:
Показывать пустые аватары

**Comment by Lion34** [comment]
Пустые аватары отключить теперь нельзя, это сделано, чтобы выровнять высоту всех контактов.

**Comment by mrlioncub** [comment]
Очень не удобно и не красиво смотрится...
Занимают лишнее место, там где может дописаться не вмещающееся имя.

**Comment by Lion34** [comment]
Показывать заглушки аватаров это стандарт де факто в мессенджерах, привычный всем и на мой взгляд выглядит лучше.

**Comment by mrlioncub** [comment]
За всех говорить не буду и за стандарты. За себя и за всю корп.сеть: не привычно, не удобно и не функционально.
Намного лучше когда есть выбор.
