### ISSUE TITLE
Отсутствуют мои контакты в контакт-листе

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#875]
Версия Vacuum-IM: 1.3.0.20151030
ОС: Windows 8.1

Не отображаются Мои контакты в контакт-листе.

Подключенно 3 клиента от одного имени, в старых версиях они отображются в новой - нет.

**Comment by Lion34** [comment]
Группа называется мои ресурсы, у меня сейчас они отображаются. У вас они точно подключены? Если вы их видите в старой версии попробуйте послать с неё сообщение на новую.

**Comment by mrlioncub** [comment]
Очень не удобно и не красиво смотрится...

**Comment by mrlioncub** [comment]
![1](https://cloud.githubusercontent.com/assets/4263967/11369843/c104fe70-92e2-11e5-9eb3-6f375d83bb7e.jpg)
При отправке сообщения появляется группа "Не в контакт листе"
После перезапуска клиента, её уже нет.

**Comment by mrlioncub** [comment]
Этой группы нет если логин указан в виде переменной!!! %USERNAME%

**Comment by Lion34** [comment]
А в чем разница получается? Пришли мне лог из консоли прихода сообщения с заголовком.

**Comment by mrlioncub** [comment]
С указанием пользователя:

``` xml
<<<< user@j.dkb74.loc/LIONCUB8-VM 20:48:39 +0 <<<<
  <message xmlns="jabber:client" from="user@j.dkb74.loc/TempH" type="chat" to="user@j.dkb74.loc/LIONCUB8-VM">
    <body>test</body>
    <active/>
  </message>

<<<< user@j.dkb74.loc/LIONCUB8-VM 20:48:39 +52 <<<<
  <presence from="user@j.dkb74.loc/TempH" type="unavailable" to="user@j.dkb74.loc/LIONCUB8-VM"/>
```

С указанием переменной:

``` xml
<<<< %USERNAME%@j.dkb74.loc/LIONCUB8-VM 20:40:46 +0 <<<<
  <message xmlns="jabber:client" from="user@j.dkb74.loc/TempH" type="chat" 
to="%USERNAME%@j.dkb74.loc/LIONCUB8-VM">
    <body>test username</body>
    <active/>
  </message>

<<<< %USERNAME%@j.dkb74.loc/LIONCUB8-VM 20:40:46 +97 <<<<
  <presence from="user@j.dkb74.loc/TempH" type="unavailable" 
to="%USERNAME%@j.dkb74.loc/LIONCUB8-VM"/>
```

**Comment by Lion34** [comment]
Переменные окружения можно использовать только в ресурсе либо в импортируемых настройках. Судя по всему у вас есть аккаунт "%USERNAME%" на сервере и  вы к нему подключаетесь.

**Comment by mrlioncub** [comment]
Нет. Более, аккаунт %USERNAME% не возможен.

**Comment by Lion34** [comment]
Такой аккаунт вполне возможен и я его спокойно создал на сервере OpenFire. Переменные окружения подставляются только в ресурсе, в других частях Jabber ID их использовать нельзя (за исключением файлов импортируемых настроек).

**Comment by mrlioncub** [comment]
Нету такого пользователя.

**Comment by mrlioncub** [comment]
Проблема аналогична https://github.com/Vacuum-IM/vacuum-im/issues/876
