### ISSUE TITLE
Не сохраняется история

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#876]
Версия Vacuum-IM: 1.3.0.20151030
ОС: Windows 8.1

Не сохраняется история
![503183b4-92ea-11e5-9528-afe781b96000](https://cloud.githubusercontent.com/assets/4263967/11437400/3667570c-950f-11e5-9351-ee8f058e83df.jpg)

**Comment by Lion34** [comment]
Скорее всего у вас включено автоматическое сохранение истории на сервере из-за чего она не попадает в локальный архив, а т.к. "стандартный архив на сервере" отключен, то из него она не читается. Вам нужно либо отключить автоматическое сохранение истории на сервере либо включить чтение истории из архива на сервере либо включить дублирование сообщений в локальном архиве в настройках истории аккаунта. Судя по тому, как плохо работает серверная история в OpenFire, лучшим вариантом может быть вообще отказаться от истории на сервере (удалить плагин с сервера) и переместить локальную историю в пользовательскую папку на сервере (последняя настройка на скриншоте).

**Comment by mrlioncub** [comment]
В старой версии была кнопочка дублировать, а здесь как?

**Comment by Lion34** [comment]
Эта настройка теперь на вкладке истории в настройках аккаунта.

**Comment by mrlioncub** [comment]
Настройки отсутствуют:
![2015-12-01 16 29 56](https://cloud.githubusercontent.com/assets/4263967/11499586/d1e907fc-9848-11e5-878b-89439e72c9e2.png)

**Comment by Lion34** [comment]
Аккаунт должен быть подключен.

2015-12-01 14:30 GMT+03:00 mr.lioncub notifications@github.com:

**Comment by mrlioncub** [comment]
Не нашел такую галочку:
![2015-12-01 21 38 56](https://cloud.githubusercontent.com/assets/4263967/11507042/fe1b37fc-9873-11e5-8b29-e4d4da4a3ecd.png)

**Comment by Lion34** [comment]
Попробуй убрать %USERNAME% из Jabber ID

2015-12-01 19:39 GMT+03:00 mr.lioncub notifications@github.com:

**Comment by mrlioncub** [comment]
Если задать не переменную, то данная настройка появляется. 
Это не решает проблемы т.к. необходим %USERNAME%

**Comment by Lion34** [comment]
%USERNAME% нельзя использовать в этом месте, сейчас он не заменяется на значение переменной окружения.

**Comment by mrlioncub** [comment]
Данный вопрос уже решался: https://github.com/Vacuum-IM/vacuum-im/issues/799
В корпоративной среде необходимо использовать %USERNAME%

**Comment by Lion34** [comment]
Да, переменные окружения нужно использовать в импортируемых настройках, тогда аккаунт создастся с нужным именем пользователя, но в настройках вакуума нельзя так использовать переменные окружения. Подробнее тут https://github.com/Vacuum-IM/vacuum-im/issues/490

**Comment by mrlioncub** [comment]
Весь список поддерживаемых настроек где можно посмотреть?

**Comment by Lion34** [comment]
Можно в файле options.xml в профиле пользователя, а можно и тут https://github.com/Vacuum-IM/vacuum-im/blob/master/src/definitions/optionvalues.h

**Comment by mrlioncub** [comment]
https://code.google.com/p/vacuum-im/source/detail?r=2416
default-options.xml - не работает.
intial и static - работают.

**Comment by mrlioncub** [comment]
С историей разобрались. Непонятки остались с default-options.xml, intial-options.xml и static-options.xml в https://github.com/Vacuum-IM/vacuum-im/issues/877
