### ISSUE TITLE
Централизованные xml настройки

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#877]
default-options.xml - не понятна роль, настройки с него не берутся, работает ли он?
initial-options.xml - отрабатывает как положено!
static-options.xml - что-то отрабатывает, что-то нет.

**Comment by mrlioncub** [comment]
1 Правильно ли я понимаю:
Из initial-options.xml берутся настройки только при отсутствии options.xml.
Из default-options.xml берутся настройки если этой опции вообще не было или она не определена, например: 

``` xml
   <field-enabled ns="37" />
```

Из static-options.xml должны браться всегда не зависимо, что стоит у клиента и в default-options.xml
2 Смысл в настройках intial если эту же функцию может выполнять default?

3 Не работает:

``` xml
 <account>
<resource type="10">%COMPUTERNAME%</resource>
 </account>
```

В options.xml стоит:

``` xml
<resource/>
```

В default-options.xml  и static-options.xml стоит значение:

``` xml
<resource type="10">%COMPUTERNAME%</resource>
```

**Comment by Lion34** [comment]
> Из initial-options.xml берутся настройки только при отсутствии options.xml.

Да, эти настройки применяются в момент создании профиля

> Из default-options.xml берутся настройки если этой опции вообще не было или она не определена

Нет, эти настройки применяются всегда при открытии профиля, но они изменяют значения настройки по умолчанию, а не фактическое, если настройка имеет явно указанное значение, то оно не изменится при изменении в default-options.xml

> Из static-options.xml должны браться всегда не зависимо, что стоит у клиента и в default-options.xml

Настройки из static-options.xml применяются каждый раз при открытии профиля

> 2 Смысл в настройках intial если эту же функцию может выполнять default?

default изменяют значения по умолчанию, а intial фактические значения

> 3 Не работает:

Как раз работает, если в default указано значение %COMPUTERNAME%, то при отсутствии явного значения в options.xml будет браться нужное значение по умолчанию.

В настройках initial и static нужно указать ns аккаунта, к которому применяется настройка, в default наоборот не нужно т.к. значения по умолчанию одинаковые для всех ns.

**Comment by mrlioncub** [comment]
3 Не работает resource из default-options.xml и static-options.xml:
![2015-12-11 11 12 34](https://cloud.githubusercontent.com/assets/4263967/11737327/0dd570f8-9ffa-11e5-8169-fd6c22a351eb.png)
![2015-12-11 11 27 42](https://cloud.githubusercontent.com/assets/4263967/11737345/3ac78a9c-9ffa-11e5-88c4-f68566b689db.png)
При этом в options.xml ничего не поменялось:
![2015-12-11 11 14 50](https://cloud.githubusercontent.com/assets/4263967/11737350/4e56adf4-9ffa-11e5-8bc9-287a89c7f0d5.png)

**Comment by Lion34** [comment]
В клиенте какой в итоге ресурс у аккаунта получился? Должен быть %COMPUTERNAME% т.к. именно такое значение установлено по умолчанию.

**Comment by mrlioncub** [comment]
в итоге: Vacuum-IM

**Comment by Lion34** [comment]
А где лежат файлы? Должны быть в папке resources.

**Comment by mrlioncub** [comment]
Всё верно в resources в папке с программой. Все остальные настройки применяются.

**Comment by Lion34** [comment]
вот такой файл у меня работает

``` xml
<options>
  <accounts>
    <default-resource type="10">%COMPUTERNAME%</default-resource>
  </accounts>
</options>
```

**Comment by mrlioncub** [comment]
Это же другая опция, которая меняет настройки по умолчанию.
Если пользователь нечаянно изменил ресурс или установлен ресурс не по умолчанию, то и через static-options.xml его нельзя будет изменить.

**Comment by Lion34** [comment]
Если нужно жестко задать ресурс аккаунту, то это нужно делать в static-options.xml вместе с созданием аккаунта для которого нужно закрепить ресурс.

``` xml
<options>
  <account ns="{48b89920-6a6e-4311-ba7c-6a5dbd4f3dcb}">
    <name type="10">%USERNAME%@localhost</name>
    <streamJid type="10">%USERNAME%@localhost</streamJid>
    <resource type="10">%COMPUTERNAME%</resource>
    <active type="1">true</active>
  </account>
</options>
```

**Comment by mrlioncub** [comment]
re. Не работает так.

**Comment by Lion34** [comment]
Правильно, не работает, надо же аккаунт в accounts добавлять :)

``` xml
<options>
  <accounts>
    <account ns="{48b89920-6a6e-4311-ba7c-6a5dbd4f3dcb}">
      <name type="10">%USERNAME%@localhost</name>
      <streamJid type="10">%USERNAME%@localhost</streamJid>
      <resource type="10">%COMPUTERNAME%</resource>
      <active type="1">true</active>
    </account>
  </accounts>
</options>
```

Вот так работает

**Comment by mrlioncub** [comment]
Конечно же в accounts, больше некуда.

``` xml
<options>
 <accounts>
  <account ns="{cb69cbfc-2e34-4085-b847-70640a4c0c7e}">
  <stream-compress type="1">true</stream-compress>
  <auto-connect type="1">true</auto-connect>
  <connection ns="DefaultConnection">
   <proxy type="10">{00000000-0000-0000-0000-000000000000}</proxy>
   <host type="10">j.jabber.loc</host>
   <cert-verify-mode type="2">0</cert-verify-mode>
   </connection>
   <name type="10">NNN</name>
   <streamJid type="10">%USERNAME%@j.jabber.loc</streamJid>
   <resource type="10">%COMPUTERNAME%</resource>
   <enable-ntlm-auth/>
   <history-duplicate type="1">true</history-duplicate>
   <auto-reconnect type="1">true</auto-reconnect>
  </account>
 </accounts>
</options>
```

Не работает!

**Comment by Lion34** [comment]
Сейчас запустил эти настройки в static-options.xml у себя и всё работает. Что именно не работает в вас?

**Comment by mrlioncub** [comment]
Всё работает кроме %COMPUTERNAME%. 
Вы ресурс где проверяете? В самом клиенте или как этот ресурс отображается на других?
Хотя без разницы... Удалите свой профиль перед применением, возможно осталось после прошлых изменений.

**Comment by Lion34** [comment]
![2015-12-23 17 01 47](https://cloud.githubusercontent.com/assets/901482/11977786/ff272b90-a996-11e5-841b-2b5ffea1bcaf.png)
Вот, ресурс MAINPC = %COMPUTERNAME% Если он такой в настройках, то он таким же будет и при подключении.

**Comment by mrlioncub** [comment]
А вот у меня:
![2015-12-23 19 05 23](https://cloud.githubusercontent.com/assets/4263967/11977849/5612e618-a9a8-11e5-8c70-c2bfe53900c3.png)
V от 30.10.2015

**Comment by Lion34** [comment]
а если любой другой настройке присвоить значение %COMPUTERNAME% какое будет значение?

**Comment by mrlioncub** [comment]
``` xml
<name type="10">%COMPUTERNAME%</name>
```
- тут всё хорошо

**Comment by Lion34** [comment]
Не, должно быть то значение, которое выдает "echo %COMPUTERNAME%" в командной строке. А если задать фиксированное значение в resource, то оно применится?

**Comment by mrlioncub** [comment]
Нашёл из-за чего странное поведение.
Если ещё указано в default-options.xml:

``` xml
<resource type="10">%COMPUTERNAME%</resource>
```

то получается эта опция почему-то игнорируется...
Если указать например в default-options.xml:

``` xml
<resource type="10">TEST</resource>
```

или вообще этот параметр удалить, то настройки берутся из static.

**Comment by Lion34** [comment]
Дефолтное значение для этой опции хранится в опции default-resource и изменять надо именно его, напрямую изменить дефолтное значение resource нельзя.

**Comment by mrlioncub** [comment]
Всё равно странное поведение. Должно браться в любом случае из static.

**Comment by Lion34** [comment]
Тут нет ошибки, просто когда в опцию записывается значение равне дефолтному, то фактически оно не записывается, а удаляется. В итоге получается, что ты сначала устанавливаешь дефолтное значение resource в %CN%, а затем записываешь в него фактическое значение равное дефолтному, в итоге оно удаляется, дальше и при запуске вакуума дефолтное значение опции  resource устанавливается равным значению default-resource, которое в свою очередь равно Vacuum-IM.

**Comment by mrlioncub** [comment]
Интересно, у каких опций еще такое поведение?

**Comment by Lion34** [comment]
Вроде других таких нет.

**Comment by mrlioncub** [comment]
Спасибо. Пробую распространять новую версию...

**Comment by dreamer2** [comment]
не применяется прокси для передачи файлов, из всех трех конфигов пробовал
скидывает на proxy.jabbim.cz
`<options>
<datastreams>
  <settings-profile ns="{00000000-0000-0000-0000-000000000000}">
   <method ns="http://jabber">
    <org/protocol/bytestreams]>
     <network-proxy type="10">{00000000-0000-0000-0000-000000000000}</network-proxy>
     <user-stream-proxy type="10">proxy.im.tikhvin.local</user-stream-proxy>
    </org/protocol/bytestreams]>
   </method>
   <method ns="http://jabber.org/protocol/bytestreams">
    <network-proxy type="10">{00000000-0000-0000-0000-000000000000}</network-proxy>
    <enable-direct-connections/>
    <enable-forward-direct/>
    <forward-direct-address/>
    <use-account-stream-proxy/>
    <use-user-stream-proxy/>
    <user-stream-proxy type="10">proxy.im.tikhvin.local</user-stream-proxy>
    <use-account-network-proxy/>
   </method>
   <method ns="http://jabber.org/protocol/ibb">
    <block-size/>
    <stanza-type/>
   </method>
  </settings-profile>
  <socks-listen-port/>
 </datastreams>
</options>
`

**Comment by Lion34** [comment]
Попробуй в дефолтные добавить:
<options>
 <datastreams>
  <settings-profile>
   <method>
    <user-stream-proxy type="10">proxy.im.tikhvin.local</user-stream-proxy>
   </method>
  </settings-profile>
 </datastreams>
</options>

Если у тебя на сервере есть такой прокси, то он должен автоматически использоваться если включена опция "Использовать jabber-proxy на вашем сервере".

**Comment by dreamer2** [comment]
Со встроенным понятно, странно что не дает применить дополнительный.
