### ISSUE TITLE
Непонятное всплывающиее сообщение

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#883]
Версия Vacuum-IM: 1.3.0.20151030
ОС: Windows 8.1

Всплывает непонятно сообщение:
![2016-01-18 08 37 30](https://cloud.githubusercontent.com/assets/4263967/12382730/1742c5e0-bdbf-11e5-8772-af15f7d26ad1.png)

Всплывает когда контакт начинает мне писать и перед этим обязательно отправил сообщение.

Как убрать его?

**Comment by Lion34** [comment]
Я исправил эту ошибку, чтобы не ждать новой сборки можно удалить настройки находящиеся в элементе <notifications>.

**Comment by mrlioncub** [comment]
Спасибо.
Но всё равно ждать 881.
