### ISSUE TITLE
Настройки профиля

### ISSUE THREAD

**Issue by alexandrroy** [vacuum-im/vacuum-im#884]
Добрый день, интересует такой вопрос, по поводу настроек профиля, есть ли возможность 

автоматически (или заранее выбранные) настраивать профиля для доменных пользователей

чтоб не делать это вручную и каждому

**Comment by Lion34** [comment]
Да, есть https://github.com/Vacuum-IM/vacuum-im/issues/490

**Comment by alexandrroy** [comment]
и как это можно организовать, вы бы не могли рассказать

**Comment by Lion34** [comment]
Как правило используется дополнительный плагин NTLM для авторизации пользователей без пароля, а само приложение распространяется с файлами импортируемых настроек в папке resources, вот тут https://github.com/Vacuum-IM/vacuum-im/issues/877 есть пример.
