### ISSUE TITLE
Предложение по метаконтактам.

### ISSUE THREAD

**Issue by Oxyd76** [vacuum-im/vacuum-im#885]
Живой пример редактирования ростера... Например есть Jabber контакт  "Igor Vanin" и где-то на другом конце ооочень большого ростера "Игорь Ванин" транспорта vk.com. Так вот что-бы их объединить в метаконтакт, нужно вручную пролистывать ростер. Поиск не поможет. Он не умеет искать две разных строки одновременно. Может имеет смысл для любого, даже одного выделенного контакта сделать пункт меню "пометить для объединения", вместо появляющегося для нескольких выделенных "объединить контакты"? Алгоритм такой: Выбираем один или несколько контактов "пометить для объединения"(каждый контакт, отдельно, легко находится поиском). После того как мы пометили первый контакт, открывается то окошко, где вписывается имя метаконтакта. При добавлении очередного, список метаконтакта обновляется. После того как все контакты найдены и помечены, жмём в окошке создания/обновления метаконтакта кнопку "Сохранить". Это ИМХО, наиболее прямой способ, что-б не городить отдельного редактора ростера с галочками, кнопочками и прочими финтифлюшками. Разумеется в этом окошке нужно и удаление ошибочно добавленного контакта сделать(чего и в текущей реализации сильно не хватает).

**Comment by Lion34** [comment]
Не, проще сделать окно с финтифлюшками, чем такое выделение.

**Comment by Oxyd76** [comment]
Ну вам виднее конечно, но мне показалось что так проще. Можно обойтись уже имеющимися формами.
