### ISSUE TITLE
Недоработка в парсере ссылок

### ISSUE THREAD

**Issue by PalmtopTiger** [vacuum-im/vacuum-im#886]
Когда ссылка оканчивается на обратный слэш, он не включается в ссылку. Есть сайты, для которых это критично. Например, https://www.linux.org.ru/news/ → https://www.linux.org.ru/news (404).
То же наблюдается с решёткой, когда после неё идёт пробел или знак препинания и, вероятно, с другими подобными символами, которые являются допустимыми для URL.

![screenshot](https://cloud.githubusercontent.com/assets/3754317/12551190/829d173e-c38a-11e5-98f2-78a3f26348bc.png)

**Comment by Lion34** [comment]
Это меньшее из возможных зол, если разрешить знаки в конце, то начнут попадать в ссылки всякие точки, запятые, двоеточия и прочее. Уже было перепробовано куча регулярных выражений, этот вариант самый лучший из возможных.

**Comment by PalmtopTiger** [comment]
Разрешите, пожалуйста, только слэш и решётку. Или хотя бы только слэш. Ссылки ломаются, приходится руками копировать.

**Comment by Lion34** [comment]
Какие-то отдельные символы можно добавить, есть предложения какие нужны?

**Comment by Lion34** [comment]
Добавил захват следующих символов в конце ссылки /#~@&=+*$

**Comment by PalmtopTiger** [comment]
Судя по https://tools.ietf.org/html/rfc3986 у нас есть такой набор допустимых для URL символов:
-._~:/?#[]@!$&'()*+,;=
Плюс, минус, подчёркивание, слэш и решётка постоянно используются в ссылках.
Квадратные скобки: http://ya.ru/?param[] является валидным URL (передача элемента массива без значения).

Пока я писал, меня посетила идея: а почему бы не спросить мнение GitHub?
http://ya.ru/-
http://ya.ru/.
http://ya.ru/_
http://ya.ru/~
http://ya.ru/:
http://ya.ru/
http://ya.ru/?
http://ya.ru/#
http://ya.ru/[
http://ya.ru/]
http://ya.ru/@
http://ya.ru/!
http://ya.ru/$
http://ya.ru/&
http://ya.ru/'
http://ya.ru/(
http://ya.ru/)
http://ya.ru/*
http://ya.ru/+
http://ya.ru/,
http://ya.ru/;
http://ya.ru/=
Видно, что не включаются знаки препинания и закрывающие скобки. Но со скобками есть тонкий момент: открывающие включаются всегда и потом включается такое же число закрывающих: http://ya.ru?param[[[]]]]]

В общем, я бы предложил не включать знаки препинания и обычные скобки. Все остальные из перечисленных символов - включать.

**Comment by PalmtopTiger** [comment]
Зря писал )))

**Comment by Lion34** [comment]
Не зря, может еще пригодится.
