### ISSUE TITLE
Падает при поиске

### ISSUE THREAD

**Issue by mkondratev** [vacuum-im/vacuum-im#887]
Проблема в зависании клиента после отправки входных данных на vjud. Тестировал на search.evalink.ru, на Pidgin проблем нет.

Ubuntu: 14.04.03 x64
Vacuum-IM: 1.3.0+git201601261003-trusty1

**Comment by Lion34** [comment]
У меня проблема не проявилась, можешь выложить куда-нибудь XML лог и лог приложения при зависании?
