### ISSUE TITLE
Проблемы с кнопкой изменения статуса

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [vacuum-im/vacuum-im#888]
1.3.0 Alpha от 30.10.2015

![vacuum-status-error](https://cloud.githubusercontent.com/assets/17122801/12913149/c3c08ee8-cf3e-11e5-9c13-03fa4705b97d.jpg)

"Изменять статус" - как-то непонятно звучит. Что означает эта кнопка? Следовать правилам автостатусов?
Раньше, в 1.3.0.2356, там было ещё "Редактировать статусы" и и по нажатии открывалось меню статусов. Это было удобно. Можно как-то вернуть?

**Comment by Lion34** [comment]
Это переключаемая кнопка, если её включить, то при каждом смене статуса будет появляться окно, где можно будет ввести текст статуса. Редактирование статусов перенесено в настройки на вкладку Статусы.
