### ISSUE TITLE
Do not display "Use native popup notification, if available" option when native notifications not available

### ISSUE THREAD

**Issue by ghost** [vacuum-im/vacuum-im#889]
Availability of  native popup notifications could be  determined at application startup, so there is no reason to display the option in notification settings. Also, if option is displayed only when feature is available, it could be shortened to "Use native popup notification" only.

Доступны ли родные уведомления, можно определить при запуске приложения, так что нет причин отображать данную опцию в настройках уведомлений, если они недоступны. Также, если опция отображается только если данная фича доступна, её можно сократить до "Use native popup notification".

**Comment by Lion34** [comment]
fixed in 1754a3cab6f843e6a2407bb6b9d9b70ca9478053
