### ISSUE TITLE
Новый пользователь не может отредактировать vcard

### ISSUE THREAD

**Issue by mkondratev** [vacuum-im/vacuum-im#890]
То есть суть. Новый пользователь не может отредактировать свою vcard. Присылает ошибку. "Не удалось загрузить личные данные. Запрашиваемый элемент не найден". Приходится редактировать через Pidgin.

Prosody: 0.10 nightly build 213 (2016-02-09, 18b7ffd08d56)
Ubuntu: 14.04.3 x64
Vacuum: 312008601a613f7f4ffe4522456bc924d6b83e2b

**Comment by Lion34** [comment]
fixed in e3f39fd45900f0c67327fc122b2b7732d0954ac1
