### ISSUE TITLE
Путь сохранения файлов

### ISSUE THREAD

**Issue by dreamer2** [vacuum-im/vacuum-im#891]
нужна возможность использовать в пути сохранения файлов переменные %appdata% %userprofile% %username%

или как минимум заполнять их один раз при настройке из initial-options.xml  `<default-dir type="10"></default-dir>`

**Comment by Lion34** [comment]
Можно использовать переменные окружения в импортируемых настройках.

**Comment by dreamer2** [comment]
что имеется в виду под импортом? из initial-options.xml  ничего не парсится

**Comment by Lion34** [comment]
Парсятся только переменные окружения.

**Comment by dreamer2** [comment]
%userprofile% %username% %appdata% это без сомнений переменные окружения? они из
`<default-dir type="10">%appdata%</default-dir>` файла initial-options.xml 
переходят в конфиг без изменений, так же переменной

**Comment by Lion34** [comment]
Попробуй заглавными буквами %APPDATA%

**Comment by dreamer2** [comment]
да, регистрозависимость мешает
заглавными все ок
