### ISSUE TITLE
Не удаётся настроить метод передачи SOCKS 5 через initial-options.xml

### ISSUE THREAD

**Issue by Casm82** [vacuum-im/vacuum-im#892]
Версия vacuum-im_1.3.0.20160221_win32-msvc2010_qt4.8.7_full, клиент Windows 8, Windows 10 x64. Сервер Openfire в домене, авторизация NTLM. Хочу настроить заранее параметры передачи файлов.  
Создаю initial-options.xml - https://gist.github.com/Casm82/31ad3e5d15f94a6bc0fd  
Все секции применяются при создании профиля, кроме настроек метода передачи SOCKS 5.
Если включить в initial-options.xml 
`<datastreams>
  <settings-profile ns="{00000000-0000-0000-0000-000000000000}">
   <method ns="http://jabber.org/protocol/bytestreams">
   </method>
 </datastreams>`
то ошибок нет, но если добавить любой параметр внутрь `method` (например, отключение прямой передачи файлов), то в options.xml при выходе записывается странные теги xml - https://gist.github.com/Casm82/35140383951ef64667d0
Должно быть `<method ns="http://jabber.org/protocol/bytestreams">` , а записывается `<method ns="http://jabber">    <org/protocol/bytestreams]>`
В итоге, параметры метода передачи SOCKS 5 не настраиваются.

Если взять версию Vacuum IM из github и собрать в Linux, то там всё работает корректно - все настройки обрабатываются. Собирать Vacuum IM под Windows не пробовал, так как не знаю как.

**Comment by Lion34** [comment]
Да, есть ошибка в импорте настроек содержащих точку в ns, не понятно почему в Linux работает

**Comment by Casm82** [comment]
Перепроверил в Linux - тоже есть ошибка. Видимо, первый раз без datastream проверял.

**Comment by Lion34** [comment]
fixed in 30497acc6e1677abd51834b32fb2f9c0ee93e1b0
