### ISSUE TITLE
Разбивка истории

### ISSUE THREAD

**Issue by eyeuser** [vacuum-im/vacuum-im#893]
В настоящий момент история группируется по месяцам.Если выбрать просмотр за месяц, то вся история выводится сплошным текстом. Но если раскрыть его, то разбивка идёт по дисконектам. то есть может быть по нескольку раз в день. Считаю что нужно группировку немного переделать - чтобы группировалось не только по целому месяцу, но ещё и по дням. А уже дни можно было бы разбить по дисконектам.
http://s017.radikal.ru/i405/1603/31/d5dccbca93cc.png

**Comment by Lion34** [comment]
Fixed in e1f9380ffe1f2ed0215335d2b47c1e25ecab0afa
