### ISSUE TITLE
error C2039: nativeLanguageName: не является членом "QLocale"

### ISSUE THREAD

**Issue by Newcss** [vacuum-im/vacuum-im#896]
Windows Visual Studio 2010. Qt 4.7.1 
При выполнении команд 
qmake CONFIG-=debug_and_release CONFIG-=debug -recursive vacuum.pro
nmake
nmake install
Сборка не проходит. Выводит ошибки:
.\optionsmanager.cpp(183) : error C2039: nativeLanguageName: не является членом "QLocale"
        c:\qt\4.7.1\include\qtcore../../src/corelib/tools/qlocale.h(110): см. объявление "QLocale"
.\optionsmanager.cpp(184) : error C2039: nativeCountryName: не является членом "QLocale"
        c:\qt\4.7.1\include\qtcore../../src/corelib/tools/qlocale.h(110): см. объявление "QLocale"

Ошибка вот тут:
## QString langName = locale.nativeLanguageName();

QString QLocale::nativeLanguageName() const
This function was introduced in Qt 4.8.

В инфе по сборке у Вас указано  QT 4.5.2

**Comment by Lion34** [comment]
А вы какую версию собираете? В мастере указано 4.8.x.
