### ISSUE TITLE
 ssl handshake failed to server with Let's Encrypte certificate

### ISSUE THREAD

**Issue by unreg** [vacuum-im/vacuum-im#901]
subj

Linux client v. 1.2.4.0, server with valid Let's Encrypte certificate, error code "14094410:SSL  handshake failure".

**Comment by Lion34** [comment]
Try latest release v1.2.5

**Comment by unreg** [comment]
In last build from github, dialog with warning check certificate "This certificate is not valid (host name mismatch)".

**Comment by Lion34** [comment]
Its seem that your certificate is not issued for domain that you use for jabber, so it is not valid.
