### ISSUE TITLE
Перестала работать авторизация NTLM в версиях Vacuum-IM новее марта 2016 с сервером Openfire

### ISSUE THREAD

**Issue by Casm82** [vacuum-im/vacuum-im#904]
Имеется сервер Openfire 4 с патчем Расмусена для авторизации через NTLM (сервер на Windows 2012 в домене).
Клиент запускается на компьютере с Windows 8, включенной в тот же домен.
Клиент Vacuum-IM собранный 1 марта 2016 успешно подключается и авторизуется без запроса пароля.
Более новые версии Vacuum-IM (проверял на 2016-03-27, 2016-06-19), при включенной авторизации NTLM, не подключаются.
Если отключить NTLM, то при ручном вводе пароля Vacuum-IM 2016-06-19 подключается успешно.
Профиль один и тот же  - options.xml https://gist.github.com/Casm82/407dd7a5b754a946ff5b819ec613d0b6
Вот вывод xml-консоли при подключении для двух версии клиентов:
- Vacuum-IM 01-03-2016 (успешно работает NTLM) - https://gist.github.com/Casm82/35596a5064d01b2b441bfac780814a16
- Vacuum-IM 19-06-2016 (при включенной NTLM, не подключается) - https://gist.github.com/Casm82/daabea058562f91a346205acaa5a5bff

**Comment by Lion34** [comment]
Исправил багу, попробуйте новую версию https://github.com/Vacuum-IM/vacuum-im/releases/tag/1.3.0.20150905-Alpha

**Comment by Casm82** [comment]
Всё отлично работает. Спасибо!
