### ISSUE TITLE
Защищенное подключение не установлено

### ISSUE THREAD

**Issue by Newcss** [vacuum-im/vacuum-im#905]
Есть OpenVPN сервер, к нему подключен Jabber-сервер (Openfire), а так же клиенты.
При подключении через OpenVPN Vacuum-IM не может создать защищенное подключение и тем самым подключиться к Jabber-серверу. Попробовал клиент Jitsi - все автоматически штатно подключилось через OpenVPN.
Может каким-нибудь способом можно получить более детальный лог об ошибке?

**Comment by Lion34** [comment]
А какая у вас версия вакуума?
