### ISSUE TITLE
Не меняется сортировка списка контактов в окне массовой отправки сообщений

### ISSUE THREAD

**Issue by ntrufanov** [vacuum-im/vacuum-im#908]
1. В настройках в "Список контактов" меняем сортировку списка контактов на "по алфавиту".
2. При отправке сообщения нескольким получателям (массовая отправка), сортировка списка контактов остается "по статусу".

Не удобно выбирать получателей, статусы у контаков меняются и список перестраивается. Можно не заметить как контакт из нижней части переместился в верхнюю и тем самым не добавив нужный контакт. Раньше отображался список выбранных пользователей, сейчас просто их число.

Версия: 1.3.0 Alpha от 12.08.16 (Linux и Windows)

**Comment by Lion34** [comment]
Fixed in 57b0c34462c2c740640b63207f2dce54338a4333
