### ISSUE TITLE
Запрос > расширение поддержки переменных в настройках.З

### ISSUE THREAD

**Issue by Yuri-01** [vacuum-im/vacuum-im#910]
Здравствуйте,

Могу вас просить реализовать поддержку переменных вида %documents%, %desktop%, %mynickname% и пр.?

(сильно помогло бы, например, при указании пути сохранения получ.файлов).

Заранее благодарен.

**Comment by Lion34** [comment]
Вы можете сейчас завести соответствующие переменные окружения и спользовать их в настройках.

**Comment by Yuri-01** [comment]
Скажите, Сергей, а приложение понимает какие-л.свои переменные?
Вроде тех, о кот.я писал выше?

(Дело в том, что переменные, предоставляемые ОС, не всегда удобны и не всегда позволяютдобиться задуманного).

**Comment by Lion34** [comment]
Подстановка переменных в настройки производится до их чтения, по этому неоткуда брать другие переменные, кроме как из окружения.

**Comment by Yuri-01** [comment]
Мне помнится, в Miranda IM/NG м.б.исп.переменные окружения (не общесистемные и не частно-пользовательские (т.е., не не те, что выдаются по SET), а свои собств. (внутренние)).
Переменная на "Документы" текущего пользователя там точно была.

**Comment by Yuri-01** [comment]
Дополнение:
Думаю там такие переменные (например, на папку Доков) бралась из ОС через Win32API

**Comment by Lion34** [comment]
Добавлена поддержка следующий параметров
"%DesktopLocation%"
"%DocumentsLocation%"
"%FontsLocation%"
"%ApplicationsLocation%"
"%MusicLocation%"
"%MoviesLocation%"
"%PicturesLocation%"
"%TempLocation%"
"%HomeLocation%"
"%DataLocation%"
"%CacheLocation%"

Описание переменных тут http://doc.qt.io/qt-4.8/qdesktopservices.html#StandardLocation-enum

fixed in 59b8c0bec1594f6e6771df4225a4b69ef050bf32

**Comment by Yuri-01** [comment]
Сергей, спасибо.

В одном не разобрадся - где можно взять обновлённый дистрибутив приложения?

**Comment by Lion34** [comment]
Вот тут новая сборка https://github.com/Vacuum-IM/vacuum-im/releases/tag/1.3.0.20160104-Alpha

**Comment by Yuri-01** [comment]
Thanks.
