### ISSUE TITLE
Панель задач

### ISSUE THREAD

**Issue by ExGeniusF** [vacuum-im/vacuum-im#911]
Здравствуйте. Возможно ли сделать, чтобы программа постоянно отображалась на панели задач (опционально) в Linux и в Windows? Использую 1.3.0 версию, но как это включить, не нашел.
В трее многие простые люди не могут его найти...

**Comment by krab** [comment]
Объединив чат со списком контактов http://i.imgur.com/W0TUNFg.png

**Comment by ExGeniusF** [comment]
Не помогло... Жму закрыть, сворачивается в трей... На панели задач исчезает...

**Comment by krab** [comment]
Кнопка свернуть http://i.imgur.com/TW0j1g6.png

**Comment by ExGeniusF** [comment]
Я то это знаю... А вот простые люди, которым установил, это не доходит... Любят по "крестику" нажимать... Не увидев, запускают заново с ярлыка, но при этом vacuum спрашивает с каким профилем запускаться, т.е. новая копия...
В Linux Debian 8 часто в трее не выходит контекстное меню и нажатие левой кнопкой по значку не выводит список контактов и тут единственный способ - это системный монитор и завершение процесса (или перезапуск оболочки linux)...
Поэтому и думаю, есть ли возможность сделать опцию, чтобы по закрытию программа также сворачивалась в панель задач... Да и очень удобно было бы также опционально выставлять, что делать при повторном запуске с ярлыка (раскрывать имеющуюся или запускать новую копию). Либо может плагин для этого кто-то может написать?

**Comment by krab** [comment]
https://github.com/Vacuum-IM/vacuum-im/releases/tag/1.3.0.20200407-Alpha
