### ISSUE TITLE
Передача файлов > задержка доступности функционала

### ISSUE THREAD

**Issue by Yuri-01** [vacuum-im/vacuum-im#912]
Здравствуйте.
Заметил, что сразу же после подкл.нового клиента, возм.обмена файлами появл.мин.через 10 (т.е., в лок.меню контакта в списке контактов пункт "Отправить Файл" отсутствует, а окне диалога соотв.кнопка отправки файла не активна).
Само подкл.происходит быстро.
По прошествии выше указанного времени передача файлов становится возможна и раб.хорошо.
Скажите, из-за чего это происходит и как исправить?

Дополнения:
1. Версия клиента - 1.3.0
2. Исп.в лок.сетях с shared roster
3. ОС - Windows 7 SP1
4. Сервер - Openfire 4.0.4 и Prosody IM 0.9.11 (on Debian 8.6)
5. Клиент находит сервер по SVR-record (DNS-server - BIND on Debian 8.6).
6. Клиент преднастраивается при помощи inital-options.xml
7. Сертификат сервера самоподписанный.

**Comment by Lion34** [comment]
Такое может быть если в ростере сразу появляется много контактов, у которых по очереди запрашиваются поддерживаемые функции, можно запросить их вручную у нужного контакта выбрав в меню "Обзорная информация", после чего все функции станут доступны.

**Comment by Yuri-01** [comment]
Понял вас.
Спасибо.
