### ISSUE TITLE
new_feature_req > transfer file > offline users

### ISSUE THREAD

**Issue by Yuri-01** [vacuum-im/vacuum-im#919]
Возм.отпарви файлов офф-лайн пользователям.
(с врем.сохранением их на сервере (по аналогии с офф-лайновыми сообщениями)).

**Comment by Lion34** [comment]
Если отправить файл в конференцию, то его пользователь сможет скачать после подключения, передачи файлов оффлайн пользователям скорее всего не будет.

**Comment by Yuri-01** [comment]
Скажите, прав.ли я понимаю, что технич.ограничений на уровне протокола для этого нет (имею в виду передачу файла офлайновому пользователю)?

**Comment by Lion34** [comment]
Передать файл как в почте нельзя, можно передать ссылку на сессию, которая позволит скачать файл когда вы оба будете онлайн.

**Comment by Yuri-01** [comment]
Понятно. Спасибо.
