### ISSUE TITLE
Автоматическое отключение от сервера при переходе компьютера в "спящее" состояние

### ISSUE THREAD

**Issue by EGD** [vacuum-im/vacuum-im#920]
Например, клиент Psi+ при закрытии крышки ноутбука автоматически отключается с сообщением: XXX изменил(а) статус на [Отключён] Компьютер вошёл в спящий режим

**Comment by EGD** [comment]
Класс Psi+:
 https://github.com/psi-plus/psi-plus-snapshots/blob/413d3e0e8e438a4a6551d1b264a04f090024e367/src/libpsi/tools/systemwatch/systemwatch_unix.cpp

**Comment by EGD** [comment]
Описание DBus интерфейса UPower.
https://upower.freedesktop.org/docs/UPower.html

**Comment by MurzNN** [comment]
Также хотелось бы иметь возможность  перехода в оффлайн при событии Away - в Pidgin очень удобно сделано: http://i.imgur.com/Ac9kCwd.png
А то постоянно забываю дома выйти в оффлайн когда на работу еду, в итоге сообщения приходят домой ;(

**Comment by EGD** [comment]
> в итоге сообщения приходят домой ;(

поставь больший приоритет ;)

> возможность перехода в оффлайн при событии Away

ну почти тоже самое
![spectacle sl3728](https://cloud.githubusercontent.com/assets/720688/22341338/e4f2aa70-e409-11e6-8872-7a59de324943.png)

**Comment by MurzNN** [comment]
Оу, точно - что-то как-то не заметил этой опции - благодарю! Поставить больший приоритет не поможет, т.к. если я дома онлайн с самым низким приоритетом, а на работе - комп выключен, то при любых приоритетах сообщение придет домой, а на работе я его не увижу. Единственная надежда его хоть как-то прочитать на работе - это когда XEP-0313 прикрутят к Вакууму, но опять же это надо телепатически будет догадаться что тебе кто-то написал и грузануть его историю.

**Comment by EGD** [comment]
https://github.com/Vacuum-IM/laptopsupport
