### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by mrkaban** [vacuum-im/vacuum-im#925]
Hello, it is impossible to download the package from here. I see the following error:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/34561746/d4df4586-734c-11e6-89b9-8f91753b604f.zip
</Key>
<RequestId>549B8DD0E74EC2A4</RequestId>
<HostId>
17+TuNelnyJcLvyd9zWUFKBX4DhlWADUpgBu2DsLxOawcDB3qCEOvVzE5Nh/xr3rcoxNNh4UYh0=
</HostId>
</Error>`

**Comment by Lion34** [comment]
fixed
