### ISSUE TITLE
Плагин Vacuum-IM

### ISSUE THREAD

**Issue by ExGeniusF** [vacuum-im/vacuum-im#929]
Здравствуйте.
Я новичок в этом деле, знающий основные некоторые азы.
Хочу модифицировать один имеющийся плагин к Vacuum-IM 1.3.0.
Навскидку установил CodeBlocks 16. При сборке тот ругается на 
include QPair
include QList
include QUuid
include QMultiMap
Понимаю, что это внешние dll. Но не могу никак нормально скомпилировать, даже после попытки привязать нужные dll.
Может я неверную программу взял для этого? На чем лучше скомпилировать?
Эту программу выбрал, рассчитывая потом на Debian такой-же плагин собрать... А этот вроде мультиплатформенный...

**Comment by krab** [comment]
Qt Creator https://packages.debian.org/search?keywords=qtcreator
