### ISSUE TITLE
patch to enable SYSTEM QXTGLOBALSHORTCUT

### ISSUE THREAD

**Issue by martinkg** [vacuum-im/vacuum-im#941]
Hi,
I'am working on a rpm package for vacuum-im on fedora.
I created a patch for vaccum-im that check and use a system installed qxtglobalshortcutversion.
https://martinkg.fedorapeople.org/Packages/vacuum/qt5/vacuum-im-unbundle-qxtglobalshortcut.patch
The patch works for me on Fedora.

Can someone please check / check if the patch is correct to be included in the git.

Thanks

**Comment by krab** [comment]
What package on Fedora 26 contains qxtglobalshortcut?

**Comment by martinkg** [comment]
there is [review request](https://bugzilla.redhat.com/show_bug.cgi?id=1504591)

**Comment by martinkg** [comment]
qxtglobalshortcut is now in Fedora [koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=25505) available.

**Comment by martinkg** [comment]
qxtgobalshortcut is now availabe in the stable Fedora 26/27/rawhide branch and can be installed with:
`dnf install qxtglobalshortcut`

**Comment by krab** [comment]
https://i.imgur.com/2k3CHqs.png

Are you sure all these dependencies should be installed? Especially qt-devel 4.8.7?

**Comment by martinkg** [comment]
Thank you for pointing out that, i have already created a new package that hopefully corrects the bug.
https://koji.fedoraproject.org/koji/packageinfo?packageID=25505
http://pkgs.fedoraproject.org/cgit/rpms/qxtglobalshortcut.git/tree/qxtglobalshortcut.spec

**Comment by krab** [comment]
Added your patch https://github.com/Vacuum-IM/vacuum-im/commit/4b48e9720a56e98a3ec4f4e1e3429587a3dd91d2 but anyway gxtlobalshortcut not working with system library. Try hotkeys like https://i.imgur.com/wYO5656.png with single modifier.

**Comment by EGD** [comment]
hmm... i see this line in vacuum log
`[Qt] QObject::connect: No such signal QxtGlobalShortcut::activated()`

**Comment by EGD** [comment]
this patch fix globalshortcut works with _qxt_ provided by system
```diff --git a/src/utils/shortcuts.cpp b/src/utils/shortcuts.cpp
index 33b65fe5..3214f5f8 100644
--- a/src/utils/shortcuts.cpp
+++ b/src/utils/shortcuts.cpp
@@ -201,7 +201,7 @@ void Shortcuts::setGlobalShortcut(const QString &AId, bool AEnabled)
        {
                shortcut = new QxtGlobalShortcut(instance());
                q->globalShortcutsId.insert(shortcut,AId);
-               connect(shortcut,SIGNAL(activated()),instance(),SLOT(onGlobalShortcutActivated()));
+               connect(shortcut,&QxtGlobalShortcut::activated,instance(),&Shortcuts::onGlobalShortcutActivated);^M
                updateGlobal(shortcut);
                emit instance()->shortcutEnabled(AId, AEnabled);
        }```
