### ISSUE TITLE
rpmlint reports E: incorrect-fsf-address

### ISSUE THREAD

**Issue by martinkg** [vacuum-im/vacuum-im#942]
Hi,

rpmlint report E: incorrect-fsf-address for 3 files in the source.

vacuum-im-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/vacuum-im-3f1cd420382a9470802b4694fa062089417f59a9/src/plugins/spellchecker/spellbackend.cpp
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

vacuum-im-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/vacuum-im-3f1cd420382a9470802b4694fa062089417f59a9/src/plugins/spellchecker/spellbackend.h
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

vacuum-im-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/vacuum-im-3f1cd420382a9470802b4694fa062089417f59a9/src/thirdparty/idle/idle.h
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

patch that corrects this: [vacuum-im-fsf-fix.patch](https://martinkg.fedorapeople.org/Packages/vacuum/qt5/vacuum-im-fsf-fix.patch)

Thanks

**Comment by EGD** [comment]
6b614dac2971af7f23347327bc99d97cf23f73c1
