### ISSUE TITLE
Port Vacuum to Qt5

### ISSUE THREAD

**Issue by EGD** [vacuum-im/vacuum-im#944]
Следующий выпуск openSUSE (15.0) будет включать openSSL 1.1.0. Qt4 эту версию не поддерживает и поддерживать не будет.

WebKit больше не поддерживается в openSUSE, программы использующие его удаляются из основного состава.
https://lists.opensuse.org/opensuse-kde/2017-12/msg00000.html

**Comment by reagentoo** [comment]
Да и генте тоже снапшот на Qt5 нужен.
https://bugs.gentoo.org/show_bug.cgi?id=642538
@Lion34 @krab
