### ISSUE TITLE
Не запоминается настройка ростера

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#950]
Текущая версия 1.3.0 Alpha от 12.01.18
Раньше работало (с какой версии перестало не запомнил).

Подключаюсь в вакууме, сворачиваю группы, оставляю несколько развернутых.
После данного https://github.com/Vacuum-IM/vacuum-im/issues/881 отключения, подключаюсь в ручную, но все группы развернуты.

**Comment by PavelGrits** [comment]
Версия клиента 1.3.0 Alfa от 05.01.2018 - такая же проблема. После каждого переподключения или поиска все группы остаются развернутыми

**Comment by Lion34** [comment]
fixed in 52c2a8c51bf79ee5ad605086091349a2351b0c55
