### ISSUE TITLE
Размер шрифта в чате при вводе сообщения

### ISSUE THREAD

**Issue by Axi77** [vacuum-im/vacuum-im#952]
Спасибо за хороший продукт.
Хотелось бы иметь возможность изменять размер шрифта в окне чата в поле ввода сообщения а то очень мелкий шрифт.
Спасибо.

**Comment by Lion34** [comment]
Fixed

**Comment by Axi77** [comment]
Скачал альфу от May 9, 2020, там нет возможности увеличить размер шрифта в окне сообщений.

**Comment by krab** [comment]
> Скачал альфу от May 9, 2020, там нет возможности увеличить размер шрифта в окне сообщений.

Можно просто навести курсор в поле ввода и увеличивать/уменьшать размер шрифта колесиком мыши. Точно также как и в веб браузерах. Применяется ко всем полям ввода в vacuum-im и даже сохраняется после перезапуска. Скриншот: https://i.imgur.com/aIhaabE.png
