### ISSUE TITLE
An error occurred while registering the account

### ISSUE THREAD

**Issue by xuchang998** [vacuum-im/vacuum-im#953]
Hello, The compiled application, but i made the following error when registering the account. What are the possible errors？The following figure:
![h60_tvh xx1 j s kfer2r](https://user-images.githubusercontent.com/42395513/48746293-d4e1dc00-eca9-11e8-9ecc-a237a5f062bb.jpg)

**Comment by xuchang998** [comment]
It's ok on the computer that compiles the program, but it's not ok on other computers

**Comment by Lion34** [comment]
What do you see in log file?

**Comment by xuchang998** [comment]
No, there are no log files
![bogd7kvz7vp7mrnzuxsqmkn](https://user-images.githubusercontent.com/42395513/48828886-deec0380-edab-11e8-80e9-d7b91b8af37c.png)

**Comment by xuchang998** [comment]
Here's another question
![5 ei e w ltcat ja sa](https://user-images.githubusercontent.com/42395513/48839274-e02a2a00-edc5-11e8-91d9-f347b5bb821b.png)

**Comment by xnamed** [comment]
About registration make sure you have `libeay32.dll` and `ssleay32.dll` or get Windows builds of OpenSSL library and put them

The log file in `C:\Users\YOURNAME\AppData\Roaming\JRuDevels\VacuumIM\logs`

About plugins make sure you put
- Qt5
```
Qt5WebKitWidgets.dll
Qt5WebKit.dll
Qt5Sql.dll
Qt5PrintSupport.dll
Qt5Multimedia.dll
Qt5MultimediaWidgets.dll
```
- Qt4
```
QtWebKit4.dll
QtSql4.dll
```

**Comment by xuchang998** [comment]
Thank you very much. My problem has been solved.
