### ISSUE TITLE
“setuppluging”have a problem

### ISSUE THREAD

**Issue by xuchang998** [vacuum-im/vacuum-im#954]
Hello, I have a problem. "setuppluging" has a problem, as shown in the figure:
![1543286080 1](https://user-images.githubusercontent.com/42395513/49054701-133e4480-f230-11e8-8d07-7dbb666f7a9c.jpg)

**Comment by YunL0ngLee** [comment]
I have the same problem!

**Comment by krab** [comment]
Click on  ` Server Message Archive 1.0 ` what it says in "dependency(ies) not found".

Here example: https://i.imgur.com/PP2xtcy.png

Also logs in ` %appdata%\JRuDevels\VacuumIM\logs ` directory might help.

**Comment by xuchang998** [comment]
![cvzv t 1032ak h v_o](https://user-images.githubusercontent.com/42395513/49057529-f0655d80-f23a-11e8-8876-91ee7beb5a30.png)
This?

**Comment by Lion34** [comment]
This plugin depends on messagearchive.dll which fails. Please, translate error message into English.

**Comment by xuchang998** [comment]
Translate into English，as follows：
Unable to load library C:/Users/Administrator/Downloads/vacuum-im/plugins/adiummessagestyle.dll：The specified program could not be found.
Unable to load library C:/Users/Administrator/Downloads/vacuum-im/plugins/filemessagearchive.dll：The specified program could not be found.
Unable to load library C:/Users/Administrator/Downloads/vacuum-im/plugins/messagearchiver.dll：The specified program could not be found.
Unable to load library C:/Users/Administrator/Downloads/vacuum-im/plugins/notifications.dll：The specified program could not be found.

**Comment by xnamed** [comment]
You have first 4 plugins failed because you must do as I told you in the previous [issue](https://github.com/Vacuum-IM/vacuum-im/issues/953#issuecomment-440684704)

once you fix them (messagearchive.dll worked) then Server Message Archive will work because depends on it.

**Comment by xuchang998** [comment]
The six ".dll "files you mentioned, I've put them in the application directory, but still，as follows：
![39f2h55 tpb i ykzczxp9](https://user-images.githubusercontent.com/42395513/49137467-78c12c80-f327-11e8-93f5-a7303b6fffab.png)
and, My compiler version is QT5.4.2

**Comment by Lion34** [comment]
Where did you download the Vacuum-IM release? Here https://github.com/Vacuum-IM/vacuum-im/releases/download/1.3.0.20180105-Alpha/vacuum-im_1.3.0.20180105_win32-msvc2015_qt5.10.0.zip ?

**Comment by xuchang998** [comment]
I downloaded it here https://github.com/Vacuum-IM/vacuum-im，Directly "git clone" to the local

**Comment by xuchang998** [comment]
There is a ".dll " file missing in the downloaded file of the url you sent (adiummessagestyle. dll).

**Comment by krab** [comment]
Because in qt 5.6 webkit was removed and replaced with qtwebengine. 
Adiummessagestyle.dll depends on webkit.
