### ISSUE TITLE
"Transfer file" : there is a problem with sending files with SOCKS5

### ISSUE THREAD

**Issue by xuchang998** [vacuum-im/vacuum-im#955]
Using socks5 to send files, the state is always "connection timeout";But there is no problem receiving files
![ottxd e_ wuimcql95 j90](https://user-images.githubusercontent.com/42395513/50220396-31313c00-03cd-11e9-8849-afd4ed60f679.png)

**Comment by mrlioncub** [comment]
https://github.com/Vacuum-IM/vacuum-im/issues/948

**Comment by Lion34** [comment]
Duplicate #948
