### ISSUE TITLE
Разворачиваются группы после поиска

### ISSUE THREAD

**Issue by mrlioncub** [vacuum-im/vacuum-im#956]
1.3.0 Alpha 12.01.18

Почти все группы в ростере свёрнуты. Начинаю поиск контакта, после выключаю поиск, группы стали все развёрнуты.

**Comment by Lion34** [comment]
Это уже пофиксил, только сборки еще нет

**Comment by mrlioncub** [comment]
Спасибо, ждём.

**Comment by samotloruser** [comment]
отличный клиент. Сергей, как помочь финансами проекту?

**Comment by Lion34** [comment]
@samotloruser, спасибо, но не надо.

**Comment by Lion34** [comment]
Duplicate #950
