### ISSUE TITLE
Поломал вакуум

### ISSUE THREAD

**Issue by dxbit** [vacuum-im/vacuum-im#963]
Установил последнюю версию вакуума. На сервере в локальной сети установлен OpenFire 4.4.2. Не получается подключится. Отключил все плагины в мессенджере. После этого программа перестала работать - в процессах есть, а окна программы нет. Переустановка не помогла.

**Comment by EGD** [comment]
удали настройки программы в пользовательском каталоге

**Comment by krab** [comment]
`%appdata%\JRuDevels\VacuumIM` в Windows
`~/.vacuum` в Linux

**Comment by dxbit** [comment]
А я думаю где-то ж должны настройки хранится. Спасибо.
