### ISSUE TITLE
Не запоминает настройки отображения на панели задач Windows

### ISSUE THREAD

**Issue by Allname** [vacuum-im/vacuum-im#965]
Версия 1.3.0 от 11.01.2019
Настройка: Показывать заначек и уведомления слетает при каждом перезапуске клиента.

**Comment by krab** [comment]
https://i.imgur.com/O6IUov5.png О какой конкретно настройке идет речь?

**Comment by Allname** [comment]
Настройка в интерфейсе Windows:
https://i.imgur.com/qabPMNG.png

**Comment by krab** [comment]
https://github.com/Vacuum-IM/vacuum-im/releases/tag/1.3.0.20200407-Alpha
