### ISSUE TITLE
fatal error: QFile: No such file or directory

### ISSUE THREAD

**Issue by hyperfield** [vacuum-im/vacuum-im#966]
When trying to compile vacuum-im with `make`, the following error appears:

```
fatal error: QFile: No such file or directory
```
Please help resolve this issue.

**Comment by krab** [comment]
What tool you use to configure: qmake, cmake? Which Qt version? Linux distro? 

Post fully log with https://pastebin.com/

**Comment by hyperfield** [comment]
I use the instructions contained in the file `INSTALL`:
```
qmake CONFIG-=debug_and_release CONFIG-=debug -recursive vacuum.pro
make
make install
```
I'm pasting the output of make here:

https://pastebin.com/bssLSeGk

**Comment by krab** [comment]
`qmake  CONFIG-=debug_and_release CONFIG-=debug CONFIG+=release INSTALL_PREFIX=/usr -recursive vacuum.pro `

**Comment by hyperfield** [comment]
It's still the same error

> In file included from qtlockedfile.cpp:41:
> qtlockedfile.h:44:10: fatal error: QFile: No such file or directory
>    44 | #include <QFile>
>       |          ^~~~~~~
>

**Comment by krab** [comment]
Install all build dependencies:
` build-essential qt5-default cmake openssl libqt5svg5-dev libqt5x11extras5-dev libx11-dev qtmultimedia5-dev zlib1g-dev libidn11-dev libxss-dev qttools5-dev-tools qttools5-dev libhunspell-dev `

and use cmake to build instead:
` mkdir build && cd build `
` cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DPLUGIN_adiummessagestyle=OFF -DSPELLCHECKER_BACKEND=HUNSPELL `

` make -j4 `
` sudo make install `

**Comment by hyperfield** [comment]
That worked, thank you.
