### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [vacuum-im/vacuum-im#977]
Thanks for the program under a free open source license! Added a program to a Russian-language site about free open source software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5/vacuum-im-jabber-xmpp-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82.html).

Please do not abandon the project! This is a very interesting program!

Will stable versions be published here?

**Comment by krab** [comment]
https://github.com/vacuum-im/vacuum-im/releases/tag/1.3.0.20200509-Alpha очень даже стабильная
